{
 "title": "rocketmq",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(rocketmq_broker_tps,Env)"
   },
   {
    "name": "cluster",
    "label": "集群",
    "query": "label_values(rocketmq_broker_tps{Env=~\"$env\"},Cluster)"
   },
   {
    "name": "broker",
    "label": "Broker名称",
    "query": "label_values(rocketmq_broker_tps{Cluster=~\"$cluster\"},broker)"
   },
   {
    "name": "topic",
    "label": "主题",
    "query": "label_values( rocketmq_producer_tps{Cluster=~\"$cluster\"}, topic)"
   },
   {
    "name": "group",
    "label": "消费组",
    "query": "label_values(rocketmq_consumer_tps{Cluster=~\"$cluster\"}, group)"
   }
  ]
 },
 "panels": [
  {
   "title": "broker发送tps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_broker_tps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "broker消费tps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_broker_qps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\"}",
     "legendFormat": " {{broker}}"
    }
   ]
  },
  {
   "title": "客户端发送tps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_producer_tps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\"}",
     "legendFormat": "{{broker}}-{{topic}}"
    }
   ]
  },
  {
   "title": "客户端发送total tps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic)(rocketmq_producer_tps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "客户端消费tps",
   "type": "graph",
   "description": "消费tps",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_consumer_tps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\",group=~\"$group\"}",
     "legendFormat": "{{broker}}-{{topic}}@{{group}}"
    }
   ]
  },
  {
   "title": "客户端消费(consumer group)total tps",
   "type": "graph",
   "description": "消费tps",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(group)(rocketmq_consumer_tps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\",group=~\"$group\"})",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "消息积压",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": " sum(rocketmq_group_diff{Cluster=\"$cluster\",Env=\"$env\",topic=~\"$topic\",group=~\"$group\"}) by (group,topic)",
     "legendFormat": "{{topic}}@{{group}}"
    }
   ]
  },
  {
   "title": "每秒发送消息大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_producer_message_size{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\"}) by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "每秒消费消息大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_consumer_message_size{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\",group=~\"$group\"}) by (topic, group)",
     "legendFormat": "{{broker}}-{{topic}}@{{group}}"
    }
   ]
  },
  {
   "title": "broker每分钟写入消息不同耗时区间趋势",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_brokeruntime_pmdt_0ms{Cluster=\"$cluster\",Env=\"$env\"})",
     "legendFormat": "0ms"
    },
    {
     "expr": "sum(rocketmq_brokeruntime_pmdt_0to10ms{Cluster=\"$cluster\",Env=\"$env\"})",
     "legendFormat": "0-10ms"
    },
    {
     "expr": "sum(rocketmq_brokeruntime_pmdt_10to50ms{Cluster=\"$cluster\",Env=\"$env\"})",
     "legendFormat": "10-50ms"
    },
    {
     "expr": "sum(rocketmq_brokeruntime_pmdt_50to100ms{Cluster=\"$cluster\",Env=\"$env\"})",
     "legendFormat": "50-100ms"
    },
    {
     "expr": "sum(rocketmq_brokeruntime_pmdt_100to200ms{Cluster=\"$cluster\",Env=\"$env\"})",
     "legendFormat": "100-200ms"
    },
    {
     "expr": "sum(rocketmq_brokeruntime_pmdt_200to500ms{Cluster=\"$cluster\",Env=\"$env\"})",
     "legendFormat": "200-500ms"
    },
    {
     "expr": "sum(rocketmq_brokeruntime_pmdt_500to1s{Cluster=\"$cluster\",Env=\"$env\"})",
     "legendFormat": "500ms-1s"
    },
    {
     "expr": "sum(rocketmq_brokeruntime_pmdt_1to2s{Cluster=\"$cluster\",Env=\"$env\"})",
     "legendFormat": "1-2s"
    },
    {
     "expr": "sum(rocketmq_brokeruntime_pmdt_2to3s{Cluster=\"$cluster\",Env=\"$env\"})",
     "legendFormat": "2-3s"
    },
    {
     "expr": "sum(rocketmq_brokeruntime_pmdt_3to4s{Cluster=\"$cluster\",Env=\"$env\"})+sum(rocketmq_brokeruntime_pmdt_4to5s{Cluster=\"$cluster\",Env=\"$env\"})+sum(rocketmq_brokeruntime_pmdt_5to10s{Cluster=\"$cluster\",Env=\"$env\"})+sum(rocketmq_brokeruntime_pmdt_10stomore{Cluster=\"$cluster\",Env=\"$env\"})",
     "legendFormat": ">3s"
    }
   ]
  },
  {
   "title": "磁盘空间使用百分比",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_commitlog_disk_ratio{Cluster=\"$cluster\",Env=\"$env\"}*100",
     "legendFormat": "{{brokerIP}}"
    }
   ]
  },
  {
   "title": "消息消费的滞后时间（存了多久才还没被消费,ms）",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(rocketmq_group_get_latency_by_storetime{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",group=~\"$group\",topic=~\"$topic\"}) by(group, topic, broker)",
     "legendFormat": "{{broker}}-{{topic}}@{{group}}"
    }
   ]
  },
  {
   "title": "消息发送等待处理耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_send_threadpoolqueue_headwait_timemills{Cluster=\"$cluster\",Env=\"$env\"}",
     "legendFormat": "broker(slow time)"
    }
   ]
  }
 ]
}