{
 "title": "rocketmq-exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(rocketmq_broker_tps,Env)"
   },
   {
    "name": "cluster",
    "label": "集群",
    "query": "label_values(rocketmq_broker_tps{Env=~\"$env\"},Cluster)"
   },
   {
    "name": "broker",
    "label": "Broker名称",
    "query": "label_values(rocketmq_broker_tps{Cluster=~\"$cluster\"},broker)"
   },
   {
    "name": "topic",
    "label": "主题",
    "query": "label_values( rocketmq_producer_tps{Cluster=~\"$cluster\"}, topic)"
   },
   {
    "name": "group",
    "label": "消费组",
    "query": "label_values(rocketmq_consumer_tps{Cluster=~\"$cluster\"}, group)"
   }
  ]
 },
 "panels": [
  {
   "title": "集群信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "集群信息",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rocketmq_broker_tps{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "集群信息"
      }
     ]
    }
   ]
  },
  {
   "title": "集群运行状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "磁盘空间使用百分比",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rocketmq_brokeruntime_commitlog_disk_ratio{Cluster=\"$cluster\",Env=\"$env\"}*100",
       "legendFormat": "{{brokerIP}}"
      }
     ]
    },
    {
     "title": "集群每分钟写入消息不同耗时区间趋势",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_0ms{Cluster=\"$cluster\",Env=\"$env\"})",
       "legendFormat": "0ms"
      },
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_0to10ms{Cluster=\"$cluster\",Env=\"$env\"})",
       "legendFormat": "0-10ms"
      },
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_10to50ms{Cluster=\"$cluster\",Env=\"$env\"})",
       "legendFormat": "10-50ms"
      },
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_50to100ms{Cluster=\"$cluster\",Env=\"$env\"})",
       "legendFormat": "50-100ms"
      },
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_100to200ms{Cluster=\"$cluster\",Env=\"$env\"})",
       "legendFormat": "100-200ms"
      },
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_200to500ms{Cluster=\"$cluster\",Env=\"$env\"})",
       "legendFormat": "200-500ms"
      },
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_500to1s{Cluster=\"$cluster\",Env=\"$env\"})",
       "legendFormat": "500ms-1s"
      },
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_1to2s{Cluster=\"$cluster\",Env=\"$env\"})",
       "legendFormat": "1-2s"
      },
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_2to3s{Cluster=\"$cluster\",Env=\"$env\"})",
       "legendFormat": "2-3s"
      },
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_3to4s{Cluster=\"$cluster\",Env=\"$env\"})+sum(rocketmq_brokeruntime_pmdt_4to5s{Cluster=\"$cluster\",Env=\"$env\"})+sum(rocketmq_brokeruntime_pmdt_5to10s{Cluster=\"$cluster\",Env=\"$env\"})+sum(rocketmq_brokeruntime_pmdt_10stomore{Cluster=\"$cluster\",Env=\"$env\"})",
       "legendFormat": ">3s"
      }
     ]
    },
    {
     "title": "可能限流的broker（写入耗时超过200ms的消息数大于0）",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rocketmq_brokeruntime_pmdt_200to500ms{Cluster=\"$cluster\",Env=\"$env\"}) by (brokerIP) + sum(rocketmq_brokeruntime_pmdt_500to1s{Cluster=\"$cluster\",Env=\"$env\"}) by (brokerIP)+sum(rocketmq_brokeruntime_pmdt_1to2s{Cluster=\"$cluster\",Env=\"$env\"}) by (brokerIP)+sum(rocketmq_brokeruntime_pmdt_2to3s{Cluster=\"$cluster\",Env=\"$env\"}) by (brokerIP)+sum(rocketmq_brokeruntime_pmdt_3to4s{Cluster=\"$cluster\",Env=\"$env\"}) by (brokerIP)+sum(rocketmq_brokeruntime_pmdt_4to5s{Cluster=\"$cluster\",Env=\"$env\"}) by (brokerIP)+sum(rocketmq_brokeruntime_pmdt_5to10s{Cluster=\"$cluster\",Env=\"$env\"}) by (brokerIP)+sum(rocketmq_brokeruntime_pmdt_10stomore{Cluster=\"$cluster\",Env=\"$env\"}) by (brokerIP)",
       "legendFormat": "{{brokerIP}}"
      }
     ]
    },
    {
     "title": "请求等待处理耗时",
     "type": "graph",
     "description": "broker收到请求后暂存队列，经过多久后才进行处理，反映broker此时的繁忙程度",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rocketmq_brokeruntime_send_threadpoolqueue_headwait_timemills{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "{{brokerIP}}-发送请求"
      },
      {
       "expr": "rocketmq_brokeruntime_pull_threadpoolqueue_headwait_timemills{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "{{brokerIP}}-拉取请求"
      },
      {
       "expr": "rocketmq_brokeruntime_query_threadpoolqueue_headwait_timemills{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "{{brokerIP}}-查询请求"
      }
     ]
    },
    {
     "title": "已提交commit log等待构建消费队列的消息大小",
     "type": "graph",
     "description": "broker收到请求后暂存队列，经过多久后才进行处理，反映broker此时的繁忙程度",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rocketmq_brokeruntime_dispatch_behind_bytes{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "{{brokerIP}}"
      }
     ]
    },
    {
     "title": "消息消费的滞后时间（发送到broker经过多少时间还未消费）",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(rocketmq_group_get_latency_by_storetime{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",group=~\"$group\",topic=~\"$topic\"}) by(group, topic, broker)",
       "legendFormat": "{{broker}}-{{topic}}@{{group}}"
      }
     ]
    },
    {
     "title": "消息状态",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "rocketmq_brokeruntime_msg_puttotal_todaymorning{Cluster=\"$cluster\",Env=\"$env\"}-rocketmq_brokeruntime_msg_puttotal_yesterdaymorning{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "昨天写入"
      },
      {
       "expr": "rocketmq_brokeruntime_msg_put_total_today_now{Cluster=\"$cluster\",Env=\"$env\"} - rocketmq_brokeruntime_msg_puttotal_todaymorning{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "今天写入"
      },
      {
       "expr": "rocketmq_brokeruntime_msg_gettotal_todaymorning{Cluster=\"$cluster\",Env=\"$env\"}-rocketmq_brokeruntime_msg_gettotal_yesterdaymorning{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "昨天读出"
      },
      {
       "expr": "rocketmq_brokeruntime_msg_gettotal_today_now{Cluster=\"$cluster\",Env=\"$env\"} - rocketmq_brokeruntime_msg_gettotal_todaymorning{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "今天读出"
      },
      {
       "expr": "rocketmq_brokeruntime_earliest_message_timestamp{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "min消息时间"
      }
     ]
    }
   ]
  },
  {
   "title": "消息吞吐量",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "broker发送tps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rocketmq_broker_tps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\"}",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "broker消费tps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rocketmq_broker_qps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\"}",
       "legendFormat": " {{broker}}"
      }
     ]
    },
    {
     "title": "客户端发送tps",
     "type": "graph",
     "gridPos": { "h": 10, "w": 15, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rocketmq_producer_tps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\"}",
       "legendFormat": "{{broker}}-{{topic}}"
      }
     ]
    },
    {
     "title": "客户端发送total tps",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(topic)(rocketmq_producer_tps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "客户端消费tps",
     "type": "graph",
     "description": "消费tps",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rocketmq_consumer_tps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\",group=~\"$group\"}",
       "legendFormat": "{{broker}}-{{topic}}@{{group}}"
      }
     ]
    },
    {
     "title": "客户端消费total tps",
     "type": "graph",
     "description": "消费tps",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(group)(rocketmq_consumer_tps{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\",group=~\"$group\"})",
       "legendFormat": "{{group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "流量大小",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "broker每秒发送消息流量大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rocketmq_producer_message_size{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\"}) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "broker每秒消费消息流量大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rocketmq_consumer_message_size{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\"}) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "Topic每秒发送消息大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rocketmq_producer_message_size{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\"}) by(topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "消费组每秒消费消息大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rocketmq_consumer_message_size{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\",group=~\"$group\"}) by (topic, group)",
       "legendFormat": "{{broker}}-{{topic}}@{{group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "积压情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "消息积压（积压量: [0, 10W]）",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": " sum(rocketmq_group_diff{Cluster=\"$cluster\",Env=\"$env\",topic=~\"$topic\",group=~\"$group\"}) by (group,topic) >= 0 and  sum(rocketmq_group_diff{Cluster=\"$cluster\",Env=\"$env\",topic=~\"$topic\",group=~\"$group\"}) by (group,topic) <= 100000",
       "legendFormat": "{{topic}}@{{group}}"
      }
     ]
    },
    {
     "title": "异常积压（积压量<0）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum(rocketmq_group_diff{Cluster=\"$cluster\",Env=\"$env\",topic=~\"$topic\",group=~\"$group\"}) by (group,topic) < 0",
       "legendFormat": "{{topic}}@{{group}}"
      }
     ]
    },
    {
     "title": "大量积压（积压量>10W）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum(rocketmq_group_diff{Cluster=\"$cluster\",Env=\"$env\",topic=~\"$topic\",group=~\"$group\"}) by (group,topic) > 100000",
       "legendFormat": "{{topic}}@{{group}}"
      }
     ]
    },
    {
     "title": "重试队列积压",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rocketmq_group_retrydiff{Cluster=\"$cluster\",Env=\"$env\",group=~\"$group\"}) by (group)",
       "legendFormat": "{{group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "消费端运行状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "消费端信息",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rocketmq_client_consume_fail_msg_count{Cluster=\"$cluster\",Env=\"$env\",group=~\"$group\",topic=~\"$topic\"}",
       "legendFormat": "消费失败"
      }
     ]
    },
    {
     "title": "消费组消费失败量变化趋势",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rocketmq_client_consume_fail_msg_count{Cluster=\"$cluster\",Env=\"$env\",group=~\"$group\", topic=~\"$topic\"}) by (group)",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "消费端拉取tps",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rocketmq_client_consumer_pull_tps{Cluster=\"$cluster\",Env=\"$env\",group=~\"$group\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}}@{{group}}@{{clientId}}"
      }
     ]
    },
    {
     "title": "消费端消费成功tps",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rocketmq_client_consume_ok_msg_tps{Cluster=\"$cluster\",Env=\"$env\",group=~\"$group\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}}@{{group}}@{{clientId}}"
      }
     ]
    },
    {
     "title": "消费端拉取平均耗时",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rocketmq_client_consumer_pull_rt{Cluster=\"$cluster\",Env=\"$env\",group=~\"$group\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}}@{{group}}@{{clientId}}"
      }
     ]
    },
    {
     "title": "消费端消费平均耗时",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rocketmq_client_consume_rt{Cluster=\"$cluster\",Env=\"$env\",group=~\"$group\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}}@{{group}}@{{clientId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "位点信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "commit log最小位点",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rocketmq_brokeruntime_commitlog_minoffset{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "{{brokerIP}}"
      }
     ]
    },
    {
     "title": "消息量",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rocketmq_brokeruntime_commitlog_maxoffset{Cluster=\"$cluster\",Env=\"$env\"} - rocketmq_brokeruntime_commitlog_minoffset{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "{{brokerIP}}"
      }
     ]
    },
    {
     "title": "commit log最大位点",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rocketmq_brokeruntime_commitlog_maxoffset{Cluster=\"$cluster\",Env=\"$env\"}",
       "legendFormat": "{{brokerIP}}"
      }
     ]
    },
    {
     "title": "Topic生产位点",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rocketmq_producer_offset{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\"}",
       "legendFormat": "topic生产位点"
      }
     ]
    },
    {
     "title": "重试队列位点",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "targets": [
      {
       "expr": "rocketmq_topic_retry_offset{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\"}",
       "legendFormat": "topic生产位点"
      }
     ]
    },
    {
     "title": "死信队列位点",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "targets": [
      {
       "expr": "rocketmq_topic_dlq_offset{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\"}",
       "legendFormat": "topic生产位点"
      }
     ]
    },
    {
     "title": "消费位点",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "rocketmq_consumer_offset{Cluster=\"$cluster\",Env=\"$env\",broker=~\"$broker\",topic=~\"$topic\"}",
       "legendFormat": "topic生产位点"
      }
     ]
    }
   ]
  }
 ]
}